spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:

        - id: auth
          uri:
            lb://auth-server
          predicates:
            - Path=/courese/auth/**
          filters:
            - RewritePath=/courese/auth/(?<segment>.*), /$\{segment}
        - id: course
          uri:
            lb://course
          predicates:
            - Path=/api/course/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: admin_route
          uri:
            lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}



    nacos:
      discovery:
        server-addr: 192.168.133.1:8848




  application:
    name: gateway
server:
  port: 88
