spring:
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      cache:
        enabled: true
        ttl: 10
        capacity: 256
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s
    gateway:
      routes:
        - id: user
          uri:
            lb://user
          predicates:
            - Path=/courese/user/**
          filters:
            - RewritePath=/courese/(?<segment>.*), /$\{segment}
        - id: peer
          uri:
            lb://peerevaluation
          predicates:
            - Path=/courese/peerevaluation/**
          filters:
            - RewritePath=/courese/(?<segment>.*), /$\{segment}
        - id: work
          uri:
            lb://work
          predicates:
            - Path=/courese/work/**
          filters:
            - RewritePath=/courese/(?<segment>.*), /$\{segment}
        - id: auth
          uri:
            lb://auth-server
          predicates:
            - Path=/courese/auth/**
          filters:
            - RewritePath=/courese/auth/(?<segment>.*), /$\{segment}
        - id: course
          uri:
            lb://course
          predicates:
            - Path=/courese/course/**
          filters:
            - RewritePath=/courese/(?<segment>.*), /$\{segment}

        - id: admin_route
          uri:
            lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}



    nacos:
      discovery:
        server-addr: 192.168.133.1:8848


sfs:
  nacos:
    server-addr: localhost:8848
    namespace:
    group: SEATA_GROUP
seata:
  enabled: true
  application-id : ${spring.application.name}
  tx-service-group: default_tx_group
  use-jdk-proxy: true
  enable-auto-data-source-proxy: true
  registry:
    type: nacos
    nacos:
      application: seata-tc-server
      server-addr: ${sfs.nacos.server-addr}
      namespace: ${sfs.nacos.namespace}
      group: ${sfs.nacos.group}
  config:
    type: nacos
    nacos:
      server-addr: ${sfs.nacos.server-addr}
      namespace: ${sfs.nacos.namespace}
      group: ${sfs.nacos.group}
  service:
    vgroupMapping:
      default_tx_group: default

  application:
    name: gateway
server:
  port: 88
