spring:
  datasource:
    username: root
    password: UAwz7620?
    url: jdbc:mysql://bj-cynosdbmysql-grp-j3h2qsj4.sql.tencentcdb.com:29746/courese_course?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.6:8848




  application:
    name: course




mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 7000